#! /bin/bash
#===============================================================
# File: record-sdcard-image.sh
# Author: Mark Gillard
# Target environment: Debian/Unix
# Description:
#   Helper script for recording/zipping new images.
#===============================================================
clear

##### SETTINGS ####
# Edit these according to your system's filesystem.
# Descriptions follow.

#sd card file descriptor
SD_CARD_FD="/dev/sdh"

#path to your src directory
#if it does not exist it will be created
SRC_DIR="/home/marzer/src"

#how much of the image to record, in megabytes
#  a good practice is to make this (end_of_last_partition+2MB)
#  e.g. if you shrink your partitions so that the last one
#  ends at 2048MB in, set this to 2050
SIZE_MB=2050

#image name properties
IMAGE_NAME="wfu-raspbian"
IMAGE_VERSION="0.4"

##### END SETTINGS ####

WFU_TOOLS_DIR="${SRC_DIR}/wfu-tools"
OUTPUT_NAME="$IMAGE_NAME-$IMAGE_VERSION"

cd "$SRC_DIR"
if [ -z "$STYLE_MARKER" ]; then
	source "$WFU_TOOLS_DIR/wfu-shell-styles.sh"
fi

echo -e "${STYLE_TITLE}          WFU-RASPBIAN IMAGE RECORDER           ${STYLE_NONE}"
echo -e "${STYLE_WARNING}This may take a while, go make a coffee! :)${STYLE_NONE}\n"

cd "$SRC_DIR"
echo -e "${STYLE_HEADING}Recording $OUTPUT_NAME.img from $SD_CARD_FD...${STYLE_NONE}"
dd if="$SD_CARD_FD" of="$SRC_DIR/$OUTPUT_NAME.img" bs=1M count="$SIZE_MB"

echo -e "${STYLE_HEADING}Creating $OUTPUT_NAME.zip...${STYLE_NONE}"
echo -n "$OUTPUT_NAME.img was generated by $USER at " > image_generated.txt
date +"%c" >> image_generated.txt
rm -f "$OUTPUT_NAME.zip" "$OUTPUT_NAME.zip.md5"
zip -9 -j "$OUTPUT_NAME.zip" "$WFU_TOOLS_DIR/README.md" "$OUTPUT_NAME.img" image_generated.txt
rm -f "$OUTPUT_NAME.img" "image_generated.txt"
md5sum "$OUTPUT_NAME.zip" > "$OUTPUT_NAME.zip.md5"

echo -e "${STYLE_SUCCESS}Finished!${STYLE_NONE}\n"
