#!/bin/sh
### BEGIN INIT INFO
# Provides: servalboot
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start serval daemon at boot time
# Description: Start serval daemon at boot time
### END INIT INFO

case "$1" in
	start)
		echo "Starting Serval daemon"
		sudo servald start
		;;

	stop)
		echo "Stopping Serval daemon"
		sudo servald stop
		;;

	*)
		echo "Usage: servalboot {start|stop}"
		exit 1
		;;
esac

exit 0
