#!/bin/sh

rm /etc/init.d/vncboot
cp vncboot /etc/init.d/vncboot
chown root:root /etc/init.d/vncboot
chmod 755 /etc/init.d/vncboot

rm /etc/init.d/servalboot
cp servalboot /etc/init.d/servalboot
chown root:root /etc/init.d/servalboot
chmod 755 /etc/init.d/servalboot

rm /etc/init.d/gpsdboot
cp gpsdboot /etc/init.d/gpsdboot
chown root:root /etc/init.d/gpsdboot
chmod 755 /etc/init.d/gpsdboot