#!/bin/sh
### BEGIN INIT INFO
# Provides: vncboot
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start VNC Server at boot time
# Description: Start VNC Server at boot time
### END INIT INFO

case "$1" in
	start)
		echo "Starting VNC Server"
		su pi -c 'vncserver :1 -geometry 1024x576'
		;;

	stop)
		echo "Stopping VNC Server"
		pkill Xtightvnc
		;;

	*)
		echo "Usage: vncboot {start|stop}"
		exit 1
		;;
esac

exit 0
