#!/bin/sh

cd /home/pi/src
rm -f -r wfu-tools
git clone -q git://github.com/WiFindUs/wfu-tools.git

cd wfu-tools
chmod 755 wfu-update
chmod 755 wfu-relink
rm -f /usr/bin/wfu-relink
rm -f /usr/bin/wfu-update
ln -s /home/pi/src/wfu-tools/wfu-relink /usr/bin/wfu-relink
ln -s /home/pi/src/wfu-tools/wfu-update /usr/bin/wfu-update
wfu-relink

make