alias wure='wfu-update; sudo reboot'
alias wuwu='wfu-update; wfu-update'
alias wusr='wfu-update; sudo wfu-setup -r'
alias rcedit='sudo nano /etc/rc.local'
alias rclog="cat /usr/local/wifindus/rc.local.log"
alias cdtools="cd /usr/local/wifindus/wfu-tools"
alias cdhome="cd /usr/local/wifindus"
alias fakegps="wfu-fake-gps"
alias hbconfig="wfu-heartbeat-config"
alias brinfo="wfu-brain-info"
alias fullinfo="wfu-brain-info; hbconfig; fakegps"

alias sshwfu1='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu1'
alias sshwfu2='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu2'
alias sshwfu3='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu3'
alias sshwfu4='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu4'
alias sshwfu5='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu5'
alias sshwfu6='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu6'
alias sshwfu7='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu7'
alias sshwfu8='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu8'
alias sshwfu9='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu9'
alias sshwfu10='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu10'
alias sshwfu11='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu11'
alias sshwfu12='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu12'
alias sshwfu13='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu13'
alias sshwfu14='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu14'
alias sshwfu15='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu15'
alias sshwfu16='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu16'
alias sshwfu17='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu17'
alias sshwfu18='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu18'
alias sshwfu19='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu19'
alias sshwfu20='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu20'
alias sshwfu21='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu21'
alias sshwfu22='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu22'
alias sshwfu23='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu23'
alias sshwfu24='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu24'
alias sshwfu25='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu25'
alias sshwfu26='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu26'
alias sshwfu27='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu27'
alias sshwfu28='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu28'
alias sshwfu29='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu29'
alias sshwfu30='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu30'
alias sshwfu31='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu31'
alias sshwfu32='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu32'
alias sshwfu33='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu33'
alias sshwfu34='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu34'
alias sshwfu35='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu35'
alias sshwfu36='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu36'
alias sshwfu37='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu37'
alias sshwfu38='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu38'
alias sshwfu39='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu39'
alias sshwfu40='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu40'
alias sshwfu41='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu41'
alias sshwfu42='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu42'
alias sshwfu43='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu43'
alias sshwfu44='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu44'
alias sshwfu45='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu45'
alias sshwfu46='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu46'
alias sshwfu47='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu47'
alias sshwfu48='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu48'
alias sshwfu49='sshpass -p "omgwtflol87" ssh -o StrictHostKeyChecking=no wifindus@wfu49'

